### ISSUE TITLE
Build error on node 13

### ISSUE THREAD

**Issue by w32zhong** [cinderblock/node-userid#2]
```
./src/userid.cc:47:42: error: no matching function for call to ‘v8::Value::Int32Value()’
```

**Comment by cinderblock** [comment]
Which version of node 13 exactly? I'm not able to reproduce: [Github Action](https://github.com/cinderblock/node-userid/commit/d79e5f9b2c26714228fd11b1b3bfd90ddd5f15cf/checks)

I also don't see `v8::Value::Int32Value()` in [`./src/userid.cc` anywhere near line 47](https://github.com/cinderblock/node-userid/blob/master/src/userid.cc#L47)...

However, looking at that line, I see the `NODE_API_MODULE` macro and the [docs call for using the `NAPI_MODULE`](https://nodejs.org/api/addons.html#addons_n_api) macro. Not sure why that discrepancy happened.

Maybe this is the problem?

**Comment by w32zhong** [comment]
My node version is v13.5.0

**Comment by cinderblock** [comment]
When exactly do you get this error? When installing `node-userid` as a dependency from npm? Or some other time? Which version of `node-userid` are you installing?

**Comment by w32zhong** [comment]
I run npm install and get this error.

**Comment by cinderblock** [comment]
This is after cloning this repo? Or npm install this repo as a dependency? Or something else?

Assuming you're trying to `npm install` inside the cloned repository, can you see how the action I published is any different than what you're trying?

Can you try replacing `NODE_API_MODULE` with `NAPI_MODULE` in that offending file?

Please, be as verbose as possible.

**Comment by cinderblock** [comment]
Well, I tried replacing `NODE_API_MODULE` with `NAPI_MODULE` in `src/userid.cc` and it [broke the builds](https://github.com/cinderblock/node-userid/runs/364932066). So, that's not it.

I'd love to help but I'm not understanding the problem you're having.

**Comment by w32zhong** [comment]
Thank you though. I have no idea. I am using ArchLinux so maybe there are other environment updates break the building.

**Comment by cinderblock** [comment]
Can you tell me all the commands you ran before `npm install`?

**Comment by w32zhong** [comment]
Below is the entire output from npm install. I did not issue any special commands before `npm install`. Or I don't think they matter.

```sh
npm install

> userid@0.3.1 install /home/tk/master-tree/proj/tkcloud/jobd/node_modules/userid
> node-gyp rebuild

make: Entering directory '/home/tk/master-tree/proj/tkcloud/jobd/node_modules/userid/build'
  CXX(target) Release/obj.target/userid/src/userid.o
In file included from ../src/userid.cc:11:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/userid.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE GroupName(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/userid.cc:47:42: error: no matching function for call to ‘v8::Value::Int32Value()’
   47 |     group = getgrgid(info[0]->Int32Value());
      |                                          ^
In file included from /home/tk/.cache/node-gyp/13.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2778:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2778 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2778:40: note:   candidate expects 1 argument, 0 provided
../src/userid.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Gids(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/userid.cc:75:47: error: no matching function for call to ‘v8::Value::ToString()’
   75 |   String::Utf8Value utfname(info[0]->ToString());
      |                                               ^
In file included from /home/tk/.cache/node-gyp/13.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2750:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2750 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
      |                                            ^~~~~~~~
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2750:44: note:   candidate expects 1 argument, 0 provided
../src/userid.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Gid(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/userid.cc:118:49: error: no matching function for call to ‘v8::Value::ToString()’
  118 |     String::Utf8Value utfname(info[0]->ToString());
      |                                                 ^
In file included from /home/tk/.cache/node-gyp/13.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2750:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2750 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
      |                                            ^~~~~~~~
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2750:44: note:   candidate expects 1 argument, 0 provided
../src/userid.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE UserName(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/userid.cc:137:41: error: no matching function for call to ‘v8::Value::Int32Value()’
  137 |     user = getpwuid(info[0]->Int32Value());
      |                                         ^
In file included from /home/tk/.cache/node-gyp/13.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2778:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2778 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2778:40: note:   candidate expects 1 argument, 0 provided
../src/userid.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Uid(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/userid.cc:155:49: error: no matching function for call to ‘v8::Value::ToString()’
  155 |     String::Utf8Value utfname(info[0]->ToString());
      |                                                 ^
In file included from /home/tk/.cache/node-gyp/13.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2750:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2750 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
      |                                            ^~~~~~~~
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:2750:44: note:   candidate expects 1 argument, 0 provided
In file included from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
../src/userid.cc: At global scope:
/home/tk/.cache/node-gyp/13.5.0/include/node/node.h:611:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  611 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/tk/.cache/node-gyp/13.5.0/include/node/node.h:645:3: note: in expansion of macro ‘NODE_MODULE_X’
  645 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/userid.cc:174:1: note: in expansion of macro ‘NODE_MODULE’
  174 | NODE_MODULE(userid, Init);
      | ^~~~~~~~~~~
In file included from /home/tk/.cache/node-gyp/13.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/userid.cc:11:
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/tk/.cache/node-gyp/13.5.0/include/node/node_object_wrap.h:84:78:   required from here
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10400 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/tk/.cache/node-gyp/13.5.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [userid.target.mk:105: Release/obj.target/userid/src/userid.o] Error 1
make: Leaving directory '/home/tk/master-tree/proj/tkcloud/jobd/node_modules/userid/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.6-arch3-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tk/master-tree/proj/tkcloud/jobd/node_modules/userid
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok
npm WARN jobd No repository field.
npm WARN jobd No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! userid@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the userid@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tk/.npm/_logs/2019-12-27T12_38_20_972Z-debug.log

```

**Comment by cinderblock** [comment]
You're using version `0.3.1` which is not supported on recent versions of node. Please update to the latest version:

```bash
npm install userid
```

**Comment by w32zhong** [comment]
Aha, thank you for pointing that out. I didn't notice that. Does `npm install` alone never try to upgrade packages in my repository? I did run `npm install` but did not specify userid explicitly.

**Comment by cinderblock** [comment]
It should respect the semver that's specified in `package.json`.

Checkout [`npm update`](https://docs.npmjs.com/cli/update.html) and [`ncu`](https://www.npmjs.com/package/npm-check-updates).
